config/routes.rb
Isawyou::Application.routes.draw do
  resources :pics

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  
  
  has_attached_file :image, styles: { medium: "320x240>"}
attr_accessible :description, :image
validates :user_id, presence: true
  validates :description, presence: true
  belongs_to :user
  validates :attachment, :attachment_content_type => { :content_type => ['image/png', 'image/jpg', 'image/gif']}, :presence => true
  
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
          :rememberable, :trackable, :validatable
  			#:recoverable, (must add mailer info to application.rb for forgot pass page to work on heroku)
 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pics, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pics }
    end
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @pic = Pic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/new
  # GET /pics/new.json
  def new
    @pic = current_user.pics.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pic }
    end
  end

  # GET /pics/1/edit
  def edit
    @pic = current_user.pics.find(params[:id])
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = current_user.pics.new(params[:pic])

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render json: @pic, status: :created, location: @pic }
      else
        format.html { render action: "new" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pics/1
  # PUT /pics/1.json
  def update
    @pic = current_user.pics.find(params[:id])

    respond_to do |format|
      if @pic.update_attributes(params[:pic])
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic = current_user.pics.find(params[:id])
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_footer.html.erb
<div class = "footer">
<small>
© 2013 <%= link_to "LadyAlice & Co.", "http://emailalice.com" %>
</small>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">I Saw You</a>
             <% link_to "I Saw You",
 root_path, class:"brand" %>
                <div class="nav-collapse">
                    <ul class="nav pull-right">
                      <% if user_signed_in? %>
                        <li><%= link_to "About", about_path %> </li>  
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <ul class="nav pull-left">
                    <li><%= link_to "About", about_path %> </li>  
                    <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
            </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	
	  <title> I Saw You</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	</head>
	<body>
	<%= render 'layouts/header' %>
   <div class="container">
             <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>
            

		<%= yield %>
		
	<%= render 'layouts/footer' %>

	</body>
</html>

app/views/pages/about.html.erb


<h1>About</h1>

<p>
I Saw You is a project to help you find that special someone you passed in the real world.
</p>

<p>
Whether it be on the bus, in a grocery market, or in a bathroom stall. 
Our hope is that you too can find that person, or perhaps you know someone on this site-- then by all means, please let them know! </p>
</p>
<p>
<h2>Rules</h2>
It's easy to be a creeper, which is why we have a few rules...<br>
<ul>
<li>Please avoid headshots, we don't want to completely invade people's privacy</li>
<li>We also want to keep some mysteriousness</li>
<li>If it is a headshot please go to <% link_to "Pixlr", "http://pixlr.com" %> to fuzzy out the face </li>
<li>If you know someone please do leave a note and tell your friend! </li>
<li>No stalking, we want a safe, fun community</li>
</ul>

app/views/pages/home.html.erb
<div class="hero-unit">
<h1>I Saw You</h1>
<p>
<img src="http://canopytek.com/images/isawyou6.png"> 
For finding your lost love. All you need is a vague photo. 

<%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-large" %>

<!--<small>本当の愛を見た？漠然とした写真をアップロードし、それらを見つける！ </small>-->
<br>

</p>




</div>

app/views/pics/_form.html.erb
<%= simple_form_for(@pic, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>
  	<%= f.input :image, label: "Upload a pic"%>
    <%= f.input :description, as: :text, input_html: { rows: "3" } %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pics/_pic.html.erb
<tr>
<td><%= image_tag pic.image(:medium) %></td>
    <td><%= pic.description %></td>
    <td><%= link_to 'Show', pic %></td>
    <% if current_user == pic.user %>
    <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
    <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<h1>Listing pics</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Pic</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render @pics %>
</tbody>
</table>

<br />

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
		<%= image_tag @pic_image %>
		<p>
  		<%= @pic.description %>
		</p>
		<p>
		<%= @pic.user.name %>
		</p>
		<% if current_user == @pic.user %>
		<%= link_to 'Edit', edit_pic_path(@pic) %> |
		<%= link_to 'Back', pics_path %>
		<% end %>
		</div>
	</div>
</div>